### ISSUE TITLE
Ampache plugin does not work anymore

### ISSUE THREAD

**Issue by Khymick** [Simounet/Rhythmbox-Ampache#1]
Hi there,

I am trying to use the ampache plugin on my system, but unfortunately, it does not work. Details about the system:

Fedora 23
rhythmbox-3.3-2.fc23.x86_64
rhythmbox-ampache-0-0.5.20150518git7415a69.fc23.x86_64

It correctly connects to my Ampache server, but when I try to start playback of any song, it simply doesn´t work. Left of the song title, a "forbidden" symbol is showed.

If you need any logs, let me know: I will provide them.

Greets,
Michael

**Comment by Simounet** [comment]
Hi Michael,
You're not on the right repository. Mine is deprecated. You're using the code from https://github.com/lotan/rhythmbox-ampache so you must copy this issue on it.
Have a nice day.
